server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: books-catalogue
          uri: lb://ms-books-catalogue
          predicates:
            - Path=/api/books/**

        - id: books-payments
          uri: lb://ms-books-payments
          predicates:
            - Path=/api/purchases/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
