server:
  port: 8081

spring:
  application:
    name: ms-books-catalogue
  datasource:
    url: jdbc:postgresql://localhost:5433/db_catalogue
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ms-books-catalogue
    description: Microservicio de catálogo de libros
    version: 1.0.0
    author: Ricardo Muñoz
